inodata_flora_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: InodataFloraBundle:Default:index }

inodata_flora_order_product:
    pattern: /admin/inodata/flora/order/product/{id}
    defaults: {_controller: InodataFloraBundle:OrderAdmin:product}
    
inodata_flora_order_products:
    pattern: /admin/inodata/flora/order/{id}/products
    defaults: {_controller: InodataFloraBundle:OrderAdmin:orderProducts}
