inodata_flora_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: InodataFloraBundle:Default:index }

inodata_flora_order_product:
    pattern: /admin/inodata/flora/order/product/{id}
    defaults: {_controller: InodataFloraBundle:OrderAdmin:product}
    
inodata_flora_order_products:
    pattern: /admin/inodata/flora/order/{id}/products
    defaults: {_controller: InodataFloraBundle:OrderAdmin:orderProducts}

inodata_flora_order_payment_contact:
    pattern: /admin/inodata/flora/order/payment/contact/{id}
    defaults: {_controller: InodataFloraBundle:OrderAdmin:paymentContact}
    
inodata_flora_order_payment_contact_create:
    pattern: /admin/inodata/flora/order/new/payment/contact
    defaults: {_controller: InodataFloraBundle:OrderAdmin:createPaymentContact}

inodata_flora_order_filter_contact_by_customer:
    pattern: /admin/inodata/flora/order/filter/contact/by/customer/{customerId}
    defaults: {_controller: InodataFloraBundle:OrderAdmin:filterPaymentContactsByCustomer}

inodata_flora_order_filter_message_by_category:
    pattern: /admin/inodata/flora/order/filter/message/by/category/{categoryId}
    defaults: {_controller: InodataFloraBundle:OrderAdmin:filterMessagesByCategory}
    
inodata_flora_order_update_totals_cost:
    pattern: /admin/inodata/flora/order/update/totals/cost
    defaults: {_controller: InodataFloraBundle:OrderAdmin:updateTotalsCost}
    
inodata_flora_distribution_filter_order_by_messenger:
    pattern: /admin/inodata/flora/distribution/filter/order/by/messenger/{messengerId}
    defaults: {_controller: InodataFloraBundle:DistributionAdmin:ordersByMessengerId}

inodata_flora_distribution_add_orders_to_messenger: 
    pattern: /admin/inodata/flora/distribution/add/order/to/messenger
    defaults: {_controller: InodataFloraBundle:DistributionAdmin:addOrdersToMessenger}
    
inodata_flora_distribution_add_preview_order_to_messenger: 
    pattern: /admin/inodata/flora/distribution/add/preview/order/to/messenger/{orderId}
    defaults: {_controller: InodataFloraBundle:DistributionAdmin:addPreviewOrderToMessenger}
    