inodata_flora_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: InodataFloraBundle:Default:index }

inodata_flora_order_product:
    pattern: /admin/inodata/flora/order/product/{id}
    defaults: {_controller: InodataFloraBundle:OrderAdmin:product}
    
inodata_flora_order_products:
    pattern: /admin/inodata/flora/order/{id}/products
    defaults: {_controller: InodataFloraBundle:OrderAdmin:orderProducts}

inodata_flora_order_payment_contact:
    pattern: /admin/inodata/flora/order/payment/contact/{id}
    defaults: {_controller: InodataFloraBundle:OrderAdmin:paymentContact}
    
inodata_flora_order_payment_contact_create:
    pattern: /admin/inodata/flora/order/new/payment/contact
    defaults: {_controller: InodataFloraBundle:OrderAdmin:createPaymentContact}

inodata_flora_order_filter_contact_by_customer:
    pattern: /admin/inodata/flora/order/filter/contact/by/customer/{customerId}
    defaults: {_controller: InodataFloraBundle:OrderAdmin:filterPaymentContactsByCustomer}