parameters:
#    inodata_flora.example.class: Inodata\FloraBundle\Example

#services:
#    inodata_flora.example:
#        class: %inodata_flora.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    inodata_mx_states_type:
        class: Inodata\FloraBundle\Form\Type\MxStatesType
        tags:
            - { name: form.type }
    inodata_emp_positions_type:
        class: Inodata\FloraBundle\Form\Type\EmpPositionsType
        tags:
            - { name: form.type }
    admin.customer:
        class: Inodata\FloraBundle\Admin\CustomerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Catálogos, label: Cliente }
        arguments: [ null, Inodata\FloraBundle\Entity\Customer, SonataAdminBundle:CRUD ]
    admin.address:
        class: Inodata\FloraBundle\Admin\AddressAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Catálogos, label: Dirección }
        arguments: [ null, Inodata\FloraBundle\Entity\Address, SonataAdminBundle:CRUD ]
    admin.partner:
        class: Inodata\FloraBundle\Admin\PartnerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Catálogos, label: Proveedores }
        arguments: [ null, Inodata\FloraBundle\Entity\Partner, SonataAdminBundle:CRUD ]
    admin.employee:
        class: Inodata\FloraBundle\Admin\EmployeeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Catálogos, label: Empleados }
        arguments: [ null, Inodata\FloraBundle\Entity\Employee, SonataAdminBundle:CRUD ]
    admin.product:
        class: Inodata\FloraBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Catálogos, label: Productos }
        arguments: [ null, Inodata\FloraBundle\Entity\Product, SonataAdminBundle:CRUD ]
    admin.product_log:
        class: Inodata\FloraBundle\Admin\ProductLogAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Catálogos, label: Control de inventario}
        arguments: [ null, Inodata\FloraBundle\Entity\ProductLog, SonataAdminBundle:CRUD ]
    
