parameters:
#    inodata_flora.example.class: Inodata\FloraBundle\Example

services:
#    inodata_flora.example:
#        class: %inodata_flora.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
